In [ ]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
#

import numpy as np
def array_maker(N):
    return np.arange(N-1,-1,-1)

In [ ]:
array_maker(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
def diagonal_maker(N):
    return np.diag(np.arange(N, 0, -1), k=0)

In [ ]:
diagonal_maker(5)

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
diagonal_maker(5).diagonal().sum()

15

In [ ]:
#Задание 3
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

koef_matrix = np.array([[4,2,1],[1,3,0],[0,5,4]])
equal_matrix = np.array([4,12,-3])

# решение математическое
np.linalg.inv(koef_matrix).dot(equal_matrix)

# решениеиз коробки
np.linalg.solve(koef_matrix, equal_matrix)



array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
# Задание 4
# В материалах занятия раздел “Задача 4 домашнего задания”

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)



next_user_stats = np.array([0, 1, 2, 0, 0, 0])


# Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [ ]:
max_cosine = -1
max_user = -1
y = 0
for i in users_stats:
    cosine_for_i = cosine(i,next_user_stats) 
    y += 1
    if cosine_for_i > max_cosine:
    max_cosine = cosine_for_i
    max_user = i
    max_number_user = y

print(f'User with max cos is {max_number_user} with vector: {max_user} and cos: {max_cosine}')

User with max cos is 8 with vector: [0 1 1 0 0 0] and cos: 0.9486832980505138
